spring:
  datasource:
    username: postgres
    password: haythem
    url: jdbc:postgresql://localhost:5432/spring_security
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: localhost
    port: 1025
    username: haythem
    password: haythem
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


application:
  security:
    jwt:
      secret-key: 91meaCW+8lFIvxbZNgTDpe/mV8O0Kjd0YYgAkB+mgHU=
      expiration: 8640000