spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
server:
  port: 8080
  servlet:
    context-path: /api/v1/

springdoc:
  default-produces-media-type: application/json
